// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
	queries: never;
	mutations:
		| { key: 'auth.login'; input: LoginArgs; result: User }
		| { key: 'auth.register'; input: RegisterArgs; result: User };
	subscriptions: never;
};

export type User = {
	id: number;
	date_created: string;
	username: string;
	email: string;
	email_verified: boolean;
	password: string;
	plan: Plan;
};

export type Plan = 'Hobby' | 'Pro' | 'Business';

export type LoginArgs = { usernameOrEmail: string; password: string };

export type RegisterArgs = { username: string; email: string; password: string };
