// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: never,
    mutations: 
        { key: "auth.login", input: LoginArgs, result: string } | 
        { key: "auth.register", input: RegisterArgs, result: string },
    subscriptions: never
};

export type LoginArgs = { usernameOrEmail: string; password: string }

export type RegisterArgs = { username: string; email: string; password: string }
