[package]
name = "voulr-prisma"
version = "0.1.0"
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
prisma-client-rust = { workspace = true }
serde = "1.0"
serde_json = "1.0"
tokio = { workspace = true, features = ["full"] }
