// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "auth.login", input: never, result: string } | 
        { key: "auth.logout", input: never, result: string } | 
        { key: "auth.register", input: never, result: string },
    mutations: never,
    subscriptions: never
};
