on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    strategy:
      matrix:
        include:
          - projectName: 'voulr-landing'
            directory: './apps/landing/.svelte-kit/cloudflare'
          - projectName: 'voulr-web'
            directory: './apps/web/.svelte-kit/cloudflare'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Setup node with cache
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run build
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: ${{ matrix.projectName }}
          directory: ${{ matrix.directory }}
          wranglerVersion: '3'
